### PR TITLE
Fix invalid formatting and autogenerate examples

### PR DESCRIPTION
**Pull request by yugr**

### CODE REVIEW

**Comment by yugr** [comment]
Looks like installation of dependencies has broken:
```
  File "/home/runner/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 577, in parse_extras
    self.line, extras = pip_shims.shims._strip_extras(self.line)
TypeError: 'NoneType' object is not callable
```

**Review by Kazhuu — CHANGES_REQUESTED** [review]
Thanks for fixing the bug! Also the update script is nice and welcome idea. Now that examples files are properly named. Could you delete duplicate pdf files to avoid confusion? Also in the readme there is `Examples` section describing examples. Could you change the new files name to there as well?

Duplicate pdf files to remove now are `0x555555555faf-0x555555557008.pdf` and `main.pdf`. 

I also fixed the pipeline here https://github.com/Kazhuu/asm2cfg/pull/29. Rebase or merge to get the errors fixed :)

**Comment by yugr** [comment]
Sorry for late update, I've addressed the points from previous review.

**Review by Kazhuu — APPROVED** [review]
Now looks great! Approved and thanks again for contributing :+1:

**Pull request merged**
